services:
  vgg_histo_redis:
    container_name: vgg_histo_redis
    image: redis
    networks:
      - vgg_histo_network

  vgg_histo_backend:
    container_name: vgg_histo_backend
    build: .
    ports:
      - 7030:8000
    volumes:
      - ./src:/app
      - ./iedl_root_dir:/iedl_root_dir
    depends_on:
      - vgg_histo_redis
    env_file:
      - .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - vgg_histo_network

  vgg_histo_celery_worker:
    container_name: vgg_histo_celery_worker
    build: .
    command: celery -A celery_tasks.process_folder worker --loglevel=info --concurrency=1
    env_file:
      - .env
    volumes:
      - ./src:/app
      - ./iedl_root_dir:/iedl_root_dir
    depends_on:
      - vgg_histo_redis
      - vgg_histo_backend
    networks:
      - vgg_histo_network

  vgg_histo_db:
    container_name: vgg_histo_db
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./setup_db_dev.sh:/docker-entrypoint-initdb.d/init_db.sh
    networks:
      - vgg_histo_network

networks:
  vgg_histo_network:
    driver: bridge

volumes:
  db_data:
