services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  icem_backend:
    container_name: icem_backend
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/.venv
      - ./iedl_root_dir:/iedl_root_dir
    depends_on:
      - redis
    environment:
      - RELOAD=true
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A src.celery_tasks.process_folder worker --loglevel=info --concurrency=1
    volumes:
      - .:/app
      - ./iedl_root_dir:/iedl_root_dir
    depends_on:
      - redis
      - icem_backend
