version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  icem_backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - redis
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A src.core.celery worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - icem_backend
  # flower:
  #   container_name: flower
  #   build: .
  #   command: celery -A src.core.celery flower --port=5555
  #   ports:
  #     - 5556:5555
  #   depends_on:
  #     - icem_backend
  #     - redis
  #     - celery_worker