services:
  redis:
    container_name: vgg_histo_redis
    image: redis
    networks:
      - vgg_histo_network
  vgg_histo_backend:
    container_name: vgg_histo_backend
    build: .
    ports:
      - 7030:8000
    volumes:
      - .:/app
      - /app/.venv
      - /mnt/persist/xtanczost/iedl_root_dir:/iedl_root_dir
    depends_on:
      - redis
    environment:
      - RELOAD=true
    networks:
      - vgg_histo_network
  celery_worker:
    container_name: vgg_histo_celery_worker
    build: .
    command: celery -A src.celery_tasks.process_folder worker --loglevel=info --concurrency=1
    volumes:
      - .:/app
      - /mnt/persist/xtanczost/iedl_root_dir:/iedl_root_dir
    depends_on:
      - redis
      - vgg_histo_backend
    networks:
      - vgg_histo_network

networks:
  vgg_histo_network:
    driver: bridge